export interface Panne {
  id?: string;  // Auto-generated by Firestore, optional when adding
  description: string;
  date: Date;  // Or use firebase.firestore.Timestamp for Firestore compatibility
  equipmentId: string;  // String reference to equipment doc ID
  technicianId: string;  // String reference to technician doc ID
  status: 'pending' | 'in-progress' | 'resolved';
}

// Add similar interfaces for Technicien and Equipement
export interface Technicien {
  id?: string;
  name: string;
  email: string;
  phone?: string;
  specialty?: string;
}

export interface Equipement {
  id?: string;
  name: string;
  model: string;
  location?: string;
  lastMaintenance?: Date;
}